### ISSUE TITLE
Create Browserlist shareable config for enforcing eBay's browser policy

### ISSUE THREAD

**Issue by seangates** [eBay/eslint-config-ebay#12]
## Description

Refer to [work done](https://github.com/eBay/ebayui-core/pull/74) in eBayUI Core components.

We should create a [shareable config](https://github.com/browserslist/browserslist#shareable-configs) to house a set of Browserlist definitions, specifically to keep eBay in lock-step around browser policy.

## Resources

[Browserlist](https://github.com/browserslist/browserslist)
[Browserlist is a Good Idea](https://css-tricks.com/browserlist-good-idea/#article-header-id-1)

**Comment by senthilp** [comment]
@mwoo @mikewoo200 Can we create a new module `browserslist-config-ebay` and expose the list of browsers? The current list can be found [here](https://github.com/eBay/ebayui-core/blob/0.2.0/package.json#L38-L50). A sample reference [browserslist-config-wordpress](https://github.com/ntwb/browserslist-config-wordpress). We can then use it across eBay projects.

It would be ideal to have it as a separate repo.

**Comment by seangates** [comment]
### It is done

https://github.com/eBay/browserslist-config
