### ISSUE TITLE
Object spread is not supported, throws Unexpected token: ...

### ISSUE THREAD

**Issue by nitinsurana** [eBay/eslint-config-ebay#13]
Please upgrade to `ecmaVersion: 9` for object spread support.

**Comment by giovannipds** [comment]
Any plan of someone doing this? This issue is from 2019, we're in 2024 lol.

@nitinsurana we can always make a PR...

**Comment by ianmcburnie** [comment]
ECMAScript was upgraded to [latest](https://github.com/eBay/eslint-config-ebay/blob/master/index.js#L9).

p.s. eslint-config-ebay is scheduled for deprecation in favor of eslint-recommended: https://github.com/eBay/eslint-config-ebay/issues/18
