### ISSUE TITLE
Proposal: Exclude functions from no-use-before-define

### ISSUE THREAD

**Issue by yomed** [eBay/eslint-config-ebay#4]
`no-use-before-define` is currently enforced here:
https://github.com/eBay/eslint-config-ebay/blob/313b3ba27209f23f87358c7e91c5ca236acf839c/rules/variables.js#L25-L26

This is good to prevent errors with hoisted variables. However, function declarations are always hoisted in their entirety, so that usage doesn't face the same issues. I suggest we consider adjusting this rule to be `[2, "nofunc"]`. More details here: https://eslint.org/docs/rules/no-use-before-define#options

**Comment by senthilp** [comment]
More than the hoisting part, this was more about consistent code style (both writing and reading). I personally prefer to have all functions defined above before I use. But we can change it based on what the general population thinks.

@mwoo @mikewoo200 What do you think? Do you want to put a simple slack poll and then check within one day?

**Comment by yomed** [comment]
@senthilp I personally follow that too, at least most of the time. I think it might come into play more with cases where you have lots of helper functions, and don't necessarily want to order them according to the exact usage order. I don't have a strong opinion on this, but I think we should consider it.

```js
function helper2() {}

function helper1() {
    helper2();
}

function helper3() {
    helper1();
}
```

**Comment by senthilp** [comment]
Agree. I remember this rule came from a couple of folks when we initially added it. I suggest that we put it in slack and close it within a day.

**Comment by mikewoo200** [comment]
I like my functions in alphabetical order and this rule can prevent that. I created a Slack poll to see what people want.

**Comment by seangates** [comment]
I tend to group them according to their "purpose". Like string utils v. date utils. So, current settings would break that, too.

Therefore, I'm okay with changing to `nofunc`.
