### ISSUE TITLE
versioning strategy

### ISSUE THREAD

**Issue by yomed** [eBay/eslint-config-ebay#8]
Updates to linting rules could often break the builds for projects that depend on this config. Can we move towards semver for this package?

Since this is already used heavily by lots of teams, I imagine it's ready for a `1.0.0` release. From there, we should consider how to version this with 1) new rules, 2) changed rules, etc.

Because of the breaking nature of this, I see other projects release frequent major versions: https://github.com/airbnb/javascript/blob/a08afd77d5d4fe6fdaae1ac9045de957ac433367/packages/eslint-config-airbnb/CHANGELOG.md

**Comment by senthilp** [comment]
Agree, will follow semver going forward. There are few other teams that have started using this package and I am waiting for feedback. We will incorporate the feedback if any (or if no feedback, then just wait till the end of Jan) and release `1.0.0`.

After that we will follow semver for subsequent releases. Hopefully, there should not be many, except for new rules for new ES features.

@mikewoo200 @mwoo Are you ok with it?

**Comment by mikewoo200** [comment]
That sounds good with me. 

We just have to figure out the criteria for major vs. minor release. Or should we never use minor?

**Comment by senthilp** [comment]
We can probably have a minor version when we introduce a new rule for a new JavaScript language feature like for e.g. aysnc iterator. The assumption is folks have not yet started using a Stage 3 feature. We can try this and see how it goes.

**Comment by mikewoo200** [comment]
We'll try it out in the next rule change. Closing this issue.
